apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- envoy-filter-ingressgateway-settings.yaml
- envoy-filter-kubeflow-userid.yaml
- envoy-filter-proxy-protocol.yaml
- gateway-authorizationpolicy.yaml
- ingress-class.yaml
- kubeflow-cluster-roles.yaml
- kubeflow-gateway.yaml
- monitoring/

# TODO switch these around again!
# - deny-all-authorizationpolicy.yaml
- DEBUGGING-allow-all-authorizationpolicy.yaml
